language: python
python:
  - "2.7"
env:
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.4.5
  - PYTHONPATH=$PYTHONPATH:$PWD DJANGO_VERSION=1.5
install: 
  - pip install --use-mirrors Django==$DJANGO_VERSION
script: 
  - django-admin.py test axes --settings=axes.test_settings
