language: python
python:
- 2.7
- 3.5
env:
- DJANGO="Django>=1.8,<1.9"
- DJANGO="Django>=1.10,<1.11"
install:
- pip install -q $DJANGO django-appconf coveralls
script:
- coverage run -a --source=axes ./manage.py test --settings axes.test_settings
- coverage report
after_success:
- coveralls
