language: python
python:
- 2.7
- 3.5
env:
- DJANGO="Django>=1.8,<1.9"
- DJANGO="Django>=1.9,<1.10"
- DJANGO="Django>=1.10,<1.11"
install:
- pip install -q $DJANGO coveralls
script:
- coverage run -a --source=axes runtests.py
- coverage run -a --source=axes runtests_proxy.py
- coverage run -a --source=axes runtests_num_proxies.py
- coverage run -a --source=axes runtests_proxy_custom_header.py
- coverage report
after_success:
- coveralls
