dist: xenial
language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3
env:
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=master
jobs:
  fast_finish: true
  allow_failures:
    - env: DJANGO=master
  include:
    - python: 3.6
      env: TOXENV=qa
    - stage: deploy
      env:
      python: 3.6
      script: skip
      deploy:
        provider: pypi
        user: jazzband
        server: https://jazzband.co/projects/django-axes/upload
        distributions: sdist bdist_wheel
        password:
          secure: TCH5tGIggL2wsWce2svMwpEpPiwVOYqq1R3uSBTexszleP0OafNq/wZk2KZEReR5w1Aq68qp5F5Eeh2ZjJTq4f9M4LtTvqQzrmyNP55DYk/uB1rBJm9b4gBgMtAknxdI2g7unkhQEDo4suuPCVofM7rrDughySNpmvlUQYDttHQ=
        skip_existing: true
        on:
          tags: true
          repo: jazzband/django-axes
          python: 3.6
install: pip install tox-travis codecov
script: tox
after_success:
  - codecov
